<?php
if ( ! defined( 'ABSPATH' ) ) {
	exit; // Exit if accessed directly.
}

$settings = array(
    array(
        'id' => 'wptoc_first_section',
        'title' => __('Display Settings', 'wptoc'),
        'page' => 'wptoc-settings',
        'section' => null
    ),
    array(
        'id' => 'wptoc_color_section',
        'title' => __('Color Settings', 'wptoc'),
        'page' => 'wptoc-settings-layout',
        'section' => null
    ),
    array(
        'id' => 'wptoc_font_section',
        'title' => __('Font Settings', 'wptoc'),
        'page' => 'wptoc-settings-layout',
        'section' => null
    ),
    array(
        'id' => 'wptoc_spacing_section',
        'title' => __('Spacing and Design Settings', 'wptoc'),
        'page' => 'wptoc-settings-layout',
        'section' => null
    )
);

$settings_fields = array(
    array(
        'id' => 'wptoc_post_types',
        'title' => esc_html__( 'Auto Display', 'wptoc' ),
        'callback' => array( $this, 'wptoc_post_types_html' ),
        'page' => 'wptoc-settings',
        'section' => 'wptoc_first_section',
        'sanitize_callback' => array( $this, 'wptoc_sanitize_post_types' ),
        'default' => 'post',
    ),
    array(
        'id' => 'wptoc_display_post_types',
        'title' => esc_html__( 'Display Specific', 'wptoc' ),
        'callback' => array( $this, 'wptoc_display_post_types_html' ),
        'page' => 'wptoc-settings',
        'section' => 'wptoc_first_section',
        'sanitize_callback' => array( $this, 'wptoc_sanitize_display_post_types' ),
    ),
    array(
        'id' => 'wptoc_display_posts',
        'title' => esc_html__( '', 'wptoc' ),
        'callback' => array( $this, 'wptoc_display_posts_html' ),
        'page' => 'wptoc-settings',
        'section' => 'wptoc_first_section',
        'sanitize_callback' => array( $this, 'wptoc_sanitize_display_posts' ),
    ),
    array(
        'id' => 'wptoc_exclude_posts',
        'title' => esc_html__( 'Exclude Specific', 'wptoc' ),
        'callback' => array( $this, 'wptoc_exclude_posts_html' ),
        'page' => 'wptoc-settings',
        'section' => 'wptoc_first_section',
        'sanitize_callback' => array( $this, 'wptoc_sanitize_exclude_posts' ),
    ),
    array(
        'id' => 'wptoc_location',
        'title' => esc_html__( 'Display Locations', 'wptoc' ),
        'callback' => array( $this, 'wptoc_location_html' ),
        'page' => 'wptoc-settings',
        'section' => 'wptoc_first_section',
        'sanitize_callback' => array( $this, 'wptoc_sanitize_location' ),
        'default' => '0',
    ),
    array(
        'id' => 'wptoc_headline',
        'title' => esc_html__( 'Headline Text', 'wptoc' ),
        'callback' => array( $this, 'wptoc_headline_html' ),
        'page' => 'wptoc-settings',
        'section' => 'wptoc_first_section',
        'default' => 'Table of Contents',
    ),
    array(
        'id' => 'wptoc_headline_tag',
        'title' => esc_html__( 'Headline Tag', 'wptoc' ),
        'callback' => array( $this, 'wptoc_headline_tag_html' ),
        'page' => 'wptoc-settings',
        'section' => 'wptoc_first_section',
        'sanitize_callback' => array( $this, 'wptoc_sanitize_headline_tag' ),
        'default' => 'span',
    ),
    array(
        'id' => 'wptoc_headings_depth',
        'title' => esc_html__( 'Headings depth', 'wptoc' ),
        'callback' => array( $this, 'wptoc_checkbox_box_html' ),
        'page' => 'wptoc-settings',
        'section' => 'wptoc_first_section',
        'args' => array( 'fieldName' => 'wptoc_headings_depth' ),
        'sanitize_callback' => array( $this, 'wptoc_sanitize_checkbox_box' ),
    ),
    array(
        'id' => 'wptoc_openhide',
        'title' => esc_html__( 'Default Open', 'wptoc' ),
        'callback' => array( $this, 'wptoc_checkbox_html' ),
        'page' => 'wptoc-settings',
        'section' => 'wptoc_first_section',
        'args' => array( 'fieldName' => 'wptoc_openhide' ),
        'default' => '1',
    ),
    array(
        'id' => 'wptoc_background_color',
        'title' => esc_html__( 'Background Color', 'wptoc' ),
        'callback' => array( $this, 'wptoc_color_picker_html' ),
        'page' => 'wptoc-settings-layout',
        'section' => 'wptoc_color_section',
        'args' => array( 'fieldName' => 'wptoc_background_color', 'fieldID' => 'wptoc_background_color' ),
        'default' => '#f8f9fb',
    ),
    array(
        'id' => 'wptoc_border_color',
        'title' => esc_html__( 'Border Color', 'wptoc' ),
        'callback' => array( $this, 'wptoc_color_picker_html' ),
        'page' => 'wptoc-settings-layout',
        'section' => 'wptoc_color_section',
        'args' => array( 'fieldName' => 'wptoc_border_color', 'fieldID' => 'wptoc_border_color' ),
        'default' => '#ededed',
    ),
    array(
        'id' => 'wptoc_color',
        'title' => esc_html__( 'Text Color', 'wptoc' ),
        'callback' => array( $this, 'wptoc_color_picker_html' ),
        'page' => 'wptoc-settings-layout',
        'section' => 'wptoc_color_section',
        'args' => array( 'fieldName' => 'wptoc_color', 'fieldID' => 'wptoc_color' ),
        'default' => '#333333',
    ),
    array(
        'id' => 'wptoc_counter_color',
        'title' => esc_html__( 'Counter Color', 'wptoc' ),
        'callback' => array( $this, 'wptoc_color_picker_html' ),
        'page' => 'wptoc-settings-layout',
        'section' => 'wptoc_color_section',
        'args' => array( 'fieldName' => 'wptoc_counter_color', 'fieldID' => 'wptoc_counter_color' ),
        'default' => '#adadad',
    ),
    array(
        'id' => 'wptoc_link_color',
        'title' => esc_html__( 'Link Color', 'wptoc' ),
        'callback' => array( $this, 'wptoc_color_picker_html' ),
        'page' => 'wptoc-settings-layout',
        'section' => 'wptoc_color_section',
        'args' => array( 'fieldName' => 'wptoc_link_color', 'fieldID' => 'wptoc_link_color' ),
        'default' => '#39383a',
    ),
    array(
        'id' => 'wptoc_link_hover_color',
        'title' => esc_html__( 'Link Hover Color', 'wptoc' ),
        'callback' => array( $this, 'wptoc_color_picker_html' ),
        'page' => 'wptoc-settings-layout',
        'section' => 'wptoc_color_section',
        'args' => array( 'fieldName' => 'wptoc_link_hover_color', 'fieldID' => 'wptoc_link_hover_color' ),
        'default' => '#39383a',
    ),
    array(
        'id' => 'wptoc_link_hover_background_color',
        'title' => esc_html__( 'Link Hover Background Color', 'wptoc' ),
        'callback' => array( $this, 'wptoc_color_picker_html' ),
        'page' => 'wptoc-settings-layout',
        'section' => 'wptoc_color_section',
        'args' => array( 'fieldName' => 'wptoc_link_hover_background_color', 'fieldID' => 'wptoc_link_hover_background_color' ),
        'default' => '#c9c9c9',
    ),
    array(
        'id' => 'wptoc_toggler_color',
        'title' => esc_html__( 'Toggler Color', 'wptoc' ),
        'callback' => array( $this, 'wptoc_color_picker_html' ),
        'page' => 'wptoc-settings-layout',
        'section' => 'wptoc_color_section',
        'args' => array( 'fieldName' => 'wptoc_toggler_color', 'fieldID' => 'wptoc_toggler_color' ),
        'default' => '#333333',
    ),
    array(
        'id' => 'wptoc_toggler_background_color',
        'title' => esc_html__( 'Toggler Background Color', 'wptoc' ),
        'callback' => array( $this, 'wptoc_color_picker_html' ),
        'page' => 'wptoc-settings-layout',
        'section' => 'wptoc_color_section',
        'args' => array( 'fieldName' => 'wptoc_toggler_background_color', 'fieldID' => 'wptoc_toggler_background_color' ),
        'default' => '#f8f9fb',
    ),
    array(
        'id' => 'wptoc_toggler_border_color',
        'title' => esc_html__( 'Toggler Border Color', 'wptoc' ),
        'callback' => array( $this, 'wptoc_color_picker_html' ),
        'page' => 'wptoc-settings-layout',
        'section' => 'wptoc_color_section',
        'args' => array( 'fieldName' => 'wptoc_toggler_border_color', 'fieldID' => 'wptoc_toggler_border_color' ),
        'default' => '#999191',
    ),
    array(
        'id' => 'wptoc_toggler_active_background_color',
        'title' => esc_html__( 'Toggler Active Background Color', 'wptoc' ),
        'callback' => array( $this, 'wptoc_color_picker_html' ),
        'page' => 'wptoc-settings-layout',
        'section' => 'wptoc_color_section',
        'args' => array( 'fieldName' => 'wptoc_toggler_active_background_color', 'fieldID' => 'wptoc_toggler_active_background_color' ),
        'default' => '#000394',
    ),
    array(
        'id' => 'wptoc_toggler_active_color',
        'title' => esc_html__( 'Toggler Active Color', 'wptoc' ),
        'callback' => array( $this, 'wptoc_color_picker_html' ),
        'page' => 'wptoc-settings-layout',
        'section' => 'wptoc_color_section',
        'args' => array( 'fieldName' => 'wptoc_toggler_active_color', 'fieldID' => 'wptoc_toggler_active_color' ),
        'default' => '#333333',
    ),
    array(
        'id' => 'wptoc_padding',
        'title' => esc_html__( 'Padding', 'wptoc' ),
        'callback' => array( $this, 'wptoc_margin_padding_border_radius_html' ),
        'page' => 'wptoc-settings-layout',
        'section' => 'wptoc_spacing_section',
        'args' => array( 'fieldName' => 'wptoc_padding', 'fieldID' => 'wptoc_padding', 'fieldLabel' => array( 'top' => 'TOP', 'right' => 'RIGHT', 'bottom' => 'BOTTOM', 'left' => 'LEFT' ) ),
        'sanitize_callback' => array( $this, 'wptoc_sanitize_margin_padding_border_radius'),
        'default' => array( 'top' => '10', 'right' => '16', 'bottom' => '10', 'left' => '16' ),
    ),
    array(
        'id' => 'wptoc_title_padding',
        'title' => esc_html__( 'Title Padding', 'wptoc' ),
        'callback' => array( $this, 'wptoc_margin_padding_border_radius_html' ),
        'page' => 'wptoc-settings-layout',
        'section' => 'wptoc_spacing_section',
        'args' => array( 'fieldName' => 'wptoc_title_padding', 'fieldID' => 'wptoc_title_padding', 'fieldLabel' => array( 'top' => 'TOP', 'right' => 'RIGHT', 'bottom' => 'BOTTOM', 'left' => 'LEFT' ) ),
        'sanitize_callback' => array( $this, 'wptoc_sanitize_margin_padding_border_radius'),
        'default' => array( 'top' => '0', 'right' => '0', 'bottom' => '10', 'left' => '0' ),
    ),
    array(
        'id' => 'wptoc_content_padding',
        'title' => esc_html__( 'Content Padding', 'wptoc' ),
        'callback' => array( $this, 'wptoc_margin_padding_border_radius_html' ),
        'page' => 'wptoc-settings-layout',
        'section' => 'wptoc_spacing_section',
        'args' => array( 'fieldName' => 'wptoc_content_padding', 'fieldID' => 'wptoc_content_padding', 'fieldLabel' => array( 'top' => 'TOP', 'right' => 'RIGHT', 'bottom' => 'BOTTOM', 'left' => 'LEFT' ) ),
        'sanitize_callback' => array( $this, 'wptoc_sanitize_margin_padding_border_radius'),
        'default' => array( 'top' => '0', 'right' => '0', 'bottom' => '0', 'left' => '0' ),
    ),
    array(
        'id' => 'wptoc_link_padding',
        'title' => esc_html__( 'Link Padding', 'wptoc' ),
        'callback' => array( $this, 'wptoc_margin_padding_border_radius_html' ),
        'page' => 'wptoc-settings-layout',
        'section' => 'wptoc_spacing_section',
        'args' => array( 'fieldName' => 'wptoc_link_padding', 'fieldID' => 'wptoc_link_padding', 'fieldLabel' => array( 'top' => 'TOP', 'right' => 'RIGHT', 'bottom' => 'BOTTOM', 'left' => 'LEFT' ) ),
        'sanitize_callback' => array( $this, 'wptoc_sanitize_margin_padding_border_radius'),
        'default' => array( 'top' => '4', 'right' => '10', 'bottom' => '4', 'left' => '18' ),
    ),
    array(
        'id' => 'wptoc_border_width',
        'title' => esc_html__( 'Border', 'wptoc' ),
        'callback' => array( $this, 'wptoc_margin_padding_border_radius_html' ),
        'page' => 'wptoc-settings-layout',
        'section' => 'wptoc_spacing_section',
        'args' => array( 'fieldName' => 'wptoc_border_width', 'fieldID' => 'wptoc_border_width', 'fieldLabel' => array( 'top' => 'TOP', 'right' => 'RIGHT', 'bottom' => 'BOTTOM', 'left' => 'LEFT' ) ),
        'sanitize_callback' => array( $this, 'wptoc_sanitize_margin_padding_border_radius'),
        'default' => array( 'top' => '1', 'right' => '1', 'bottom' => '1', 'left' => '1' ),
    ),
    array(
        'id' => 'wptoc_border_radius',
        'title' => esc_html__( 'Radius', 'wptoc' ),
        'callback' => array( $this, 'wptoc_margin_padding_border_radius_html' ),
        'page' => 'wptoc-settings-layout',
        'section' => 'wptoc_spacing_section',
        'args' => array( 'fieldName' => 'wptoc_border_radius', 'fieldID' => 'wptoc_border_radius', 'fieldLabel' => array( 'top' => 'TOP LEFT', 'right' => 'TOP RIGHT', 'bottom' => 'BOTTOM RIGHT', 'left' => 'BOTTOM LEFT' ) ),
        'sanitize_callback' => array( $this, 'wptoc_sanitize_margin_padding_border_radius'),
        'default' => array( 'top' => '5', 'right' => '5', 'bottom' => '5', 'left' => '5' ),
    ),
    array(
        'id' => 'wptoc_toggler_padding',
        'title' => esc_html__( 'Toggler Padding', 'wptoc' ),
        'callback' => array( $this, 'wptoc_margin_padding_border_radius_html' ),
        'page' => 'wptoc-settings-layout',
        'section' => 'wptoc_spacing_section',
        'args' => array( 'fieldName' => 'wptoc_toggler_padding', 'fieldID' => 'wptoc_toggler_padding', 'fieldLabel' => array( 'top' => 'TOP', 'right' => 'RIGHT', 'bottom' => 'BOTTOM', 'left' => 'LEFT' ) ),
        'sanitize_callback' => array( $this, 'wptoc_sanitize_margin_padding_border_radius'),
        'default' => array( 'top' => '0', 'right' => '0', 'bottom' => '0', 'left' => '0' ),
    ),
    array(
        'id' => 'wptoc_toggler_border_width',
        'title' => esc_html__( 'Toggler Border', 'wptoc' ),
        'callback' => array( $this, 'wptoc_margin_padding_border_radius_html' ),
        'page' => 'wptoc-settings-layout',
        'section' => 'wptoc_spacing_section',
        'args' => array( 'fieldName' => 'wptoc_toggler_border_width', 'fieldID' => 'wptoc_toggler_border_width', 'fieldLabel' => array( 'top' => 'TOP', 'right' => 'RIGHT', 'bottom' => 'BOTTOM', 'left' => 'LEFT' ) ),
        'sanitize_callback' => array( $this, 'wptoc_sanitize_margin_padding_border_radius'),
        'default' => array( 'top' => '0', 'right' => '0', 'bottom' => '0', 'left' => '0' ),
    ),
    array(
        'id' => 'wptoc_toggler_border_radius',
        'title' => esc_html__( 'Toggler Radius', 'wptoc' ),
        'callback' => array( $this, 'wptoc_margin_padding_border_radius_html' ),
        'page' => 'wptoc-settings-layout',
        'section' => 'wptoc_spacing_section',
        'args' => array( 'fieldName' => 'wptoc_toggler_border_radius', 'fieldID' => 'wptoc_toggler_border_radius', 'fieldLabel' => array( 'top' => 'TOP LEFT', 'right' => 'TOP RIGHT', 'bottom' => 'BOTTOM RIGHT', 'left' => 'BOTTOM LEFT' ) ),
        'sanitize_callback' => array( $this, 'wptoc_sanitize_margin_padding_border_radius'),
        'default' => array( 'top' => '5', 'right' => '5', 'bottom' => '5', 'left' => '5' ),
    ),
    array(
        'id' => 'wptoc_font_size',
        'title' => esc_html__( 'Font Size', 'wptoc' ),
        'callback' => array( $this, 'wptoc_pmbr_html' ),
        'page' => 'wptoc-settings-layout',
        'section' => 'wptoc_font_section',
        'args' => array( 'fieldName' => 'wptoc_font_size', 'fieldID' => 'wptoc_font_size' ),
        'default' => '17px',
    ),
    array(
        'id' => 'wptoc_font_size_tablet',
        'title' => esc_html__( 'Font Size Tablet', 'wptoc' ),
        'callback' => array( $this, 'wptoc_pmbr_html' ),
        'page' => 'wptoc-settings-layout',
        'section' => 'wptoc_font_section',
        'args' => array( 'fieldName' => 'wptoc_font_size_tablet', 'fieldID' => 'wptoc_font_size_tablet', 'fieldLabel' => '%' ),
        'default' => '2%',
    ),
    array(
        'id' => 'wptoc_font_size_mobile',
        'title' => esc_html__( 'Font Size Mobile', 'wptoc' ),
        'callback' => array( $this, 'wptoc_pmbr_html' ),
        'page' => 'wptoc-settings-layout',
        'section' => 'wptoc_font_section',
        'args' => array( 'fieldName' => 'wptoc_font_size_mobile', 'fieldID' => 'wptoc_font_size_mobile', 'fieldLabel' => '%' ),
        'default' => '2%',
    ),
    array(
        'id' => 'wptoc_font_weight',
        'title' => esc_html__( 'Font Weight', 'wptoc' ),
        'callback' => array( $this, 'wptoc_text_font_weight_html' ),
        'page' => 'wptoc-settings-layout',
        'section' => 'wptoc_font_section',
        'args' => array( 'fieldName' => 'wptoc_font_weight', 'fieldID' => 'wptoc_font_weight' ),
        'default' => '600',
    ),
    array(
        'id' => 'wptoc_line_height',
        'title' => esc_html__( 'Line Height', 'wptoc' ),
        'callback' => array( $this, 'wptoc_text_font_weight_html' ),
        'page' => 'wptoc-settings-layout',
        'section' => 'wptoc_font_section',
        'args' => array( 'fieldName' => 'wptoc_line_height', 'fieldID' => 'wptoc_line_height' ),
        'default' => '1.1',
    ),
    array(
        'id' => 'wptoc_title_font_size',
        'title' => esc_html__( 'Title Font Size', 'wptoc' ),
        'callback' => array( $this, 'wptoc_pmbr_html' ),
        'page' => 'wptoc-settings-layout',
        'section' => 'wptoc_font_section',
        'args' => array( 'fieldName' => 'wptoc_title_font_size', 'fieldID' => 'wptoc_title_font_size' ),
        'default' => '15px',
    ),
    array(
        'id' => 'wptoc_title_font_size_tablet',
        'title' => esc_html__( 'Title Font Size Tablet', 'wptoc' ),
        'callback' => array( $this, 'wptoc_pmbr_html' ),
        'page' => 'wptoc-settings-layout',
        'section' => 'wptoc_font_section',
        'args' => array( 'fieldName' => 'wptoc_title_font_size_tablet', 'fieldID' => 'wptoc_title_font_size_tablet', 'fieldLabel' => '%' ),
        'default' => '7%',
    ),
    array(
        'id' => 'wptoc_title_font_size_mobile',
        'title' => esc_html__( 'Title Font Size Mobile', 'wptoc' ),
        'callback' => array( $this, 'wptoc_pmbr_html' ),
        'page' => 'wptoc-settings-layout',
        'section' => 'wptoc_font_section',
        'args' => array( 'fieldName' => 'wptoc_title_font_size_mobile', 'fieldID' => 'wptoc_title_font_size_mobile', 'fieldLabel' => '%' ),
        'default' => '5%',
    ),
    array(
        'id' => 'wptoc_title_font_weight',
        'title' => esc_html__( 'Title Font Weight', 'wptoc' ),
        'callback' => array( $this, 'wptoc_text_font_weight_html' ),
        'page' => 'wptoc-settings-layout',
        'section' => 'wptoc_font_section',
        'args' => array( 'fieldName' => 'wptoc_title_font_weight', 'fieldID' => 'wptoc_title_font_weight' ),
        'default' => '700',
    ),
    array(
        'id' => 'wptoc_title_line_height',
        'title' => esc_html__( 'Title Line Height', 'wptoc' ),
        'callback' => array( $this, 'wptoc_text_font_weight_html' ),
        'page' => 'wptoc-settings-layout',
        'section' => 'wptoc_font_section',
        'args' => array( 'fieldName' => 'wptoc_title_line_height', 'fieldID' => 'wptoc_title_line_height' ),
        'default' => '2.0',
    ),
);

/** 
 * Section
 * 
 */
foreach ($settings as $setting) {
    add_settings_section($setting['id'], $setting['title'], $setting['section'], $setting['page']);
}

/** 
 * Field
 * 
 */
foreach ($settings_fields as $field) {
    add_settings_field( $field['id'], $field['title'], $field['callback'], $field['page'], $field['section'], isset($field['args']) ? $field['args'] : '' );
    register_setting( 'tableofcontent', $field['id'], array( 'sanitize_callback' => isset($field['sanitize_callback']) ? $field['sanitize_callback'] : 'sanitize_text_field', 'default' => isset($field['default']) ? $field['default'] : '' ) );
}